### ISSUE TITLE
pcg still test ./vendor/...

### ISSUE THREAD

**Issue by MarcMagnin** [maruel/pre-commit-go#24]
Hey,
Thanks for that tool.

I'm trying to get some pre-commit task running tests but it still looks to run some from vendor folder:
```
...
20:33:00.808314 [go test -timeout 5s -short ./vendor/golang.org/x/net/http2] was slow: 3.249s
```

Config is pretty much the default one:
```
min_version: 0.4.7
modes:
  continuous-integration:
    checks:
      coverage:
      - use_global_inference: false
        use_coveralls: true
        global:
          min_coverage: 50
          max_coverage: 100
        per_dir_default:
          min_coverage: 1
          max_coverage: 100
        per_dir: {}
        ignore_path_patterns: [vendor]
      goimports:
      - {}
      test:
      - extra_args:
        - -v
        - -race
    max_duration: 120
  lint:
    checks:
      errcheck:
      - ignores: Close
      golint:
      - blacklist: []
      govet:
      - blacklist:
        - ' composite literal uses unkeyed fields'
    max_duration: 15
  pre-commit:
    checks:
      test:
      - extra_args:
        - -short
    max_duration: 5
  pre-push:
    checks:
      coverage:
      - use_global_inference: false
        use_coveralls: false
        global:
          min_coverage: 50
          max_coverage: 100
        per_dir_default:
          min_coverage: 1
          max_coverage: 100
        per_dir: {}
        ignore_path_patterns: [vendor]
      goimports:
      - {}
      test:
      - extra_args:
        - -v
        - -race
    max_duration: 15
ignore_patterns:
- vendor
- .*
- _*
- '*.pb.go'
- '*_string.go'
```

I've tried various things without success.
Many thanks!
